[tool.poetry]
name = "openfast_io"
version = "4.0.0" # We can make this dynamic to use github tags using dynamic = ["version"]
description = "Readers and writers for OpenFAST files."
requires-python = ">=3.9"
license = "Apache-2.0"
authors = [
    "NREL WISDEM Team <systems.engineering@nrel.gov>",
    "Daniel Zalkind <daniel.zalkind@nrel.gov>",
    "Garrett Barter <garrett.barter@nrel.gov>",
    "Pietro Bortolotti <ptrbortolotti@gmail.com>",
    "Mayank Chetan <mayank.chetan@nrel.gov>",
    "John Jasa",
]
readme = "README.md"
packages = [{include = "openfast_io"}]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1"
pandas = "^2"
xlrd = "^2"
ruamel_yaml = "^0.18"
rosco = {version = "^2.9.2", optional = true}


[tool.poetry.extras]
rosco = ["rosco"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
